# train_model_dir: applicable only if mode == [transfer|test]
# globals.java_log_destination: [none, stdout, file, stdout-file] - if file, logs are written to a file, if stdout-file, logs are written to both stdout and a file
# globals.junit_output_show: [true, false] - if true, junit test results are printed to stdout
# globals.java_log_level: [TRACE, DEBUG, INFO, WARNING, ERROR]
# seed: random or any integer
# base_log_dir: parent directory for all logs
# experiment_dir: parent directory for a set of experiments
# experiment_name: name of the experiment
# mode: [train, test, transfer]
# vm_allocation_policy: [rl, rule-based]
# cloudlet_to_dc_assignment_policy: [earliest-shortest-to-most-free-dc, random-to-most-free-dc, earliest-most-critical-to-nearest-dc, rl]
# cloudlet_to_vm_assignment_policy: [most-free-cores]
# algorithm: [any stable-baselines3 or sb3-contrib algorithm if vm_allocation_policy == rl, minimize-queue, minimize-allocated, minimize-unutilized if vm_allocation_policy == rule-based]

# globals.run_mode: [batch, serial]

# if you make any changes in java_log_leve, java_log_destination or java_output_show, 
#  you need to execute make build-gateway for the changes to take effect
globals:
    attached: true
    gpu: true
    java_log_level: DEBUG
    java_log_destination: file
    junit_output_show: false
    run_mode: serial

common:
  datacenters:
      - !datacenter
        name: cloud_dc
        type: cloud
        amount: 1
        hosts:
          - !host
            amount: 16
            pes: 64
            pe_mips: 60
            ram: 65536
            storage: 4000000
            bw: 100000
            vms:
              - !vm
                amount: 1
                pes: 64
                pe_mips: 60
                ram: 65536
                size: 4000000
                bw: 100000
      - !datacenter
        name: edge_dc_frankfurt
        type: edge
        amount: 1
        hosts:
          - !host
              amount: 8
              pes: 16
              pe_mips: 60
              ram: 65536
              storage: 2000000
              bw: 10000
              vms:
                !vm
                  amount: 1
                  pes: 16
                  pe_mips: 60
                  ram: 65536
                  size: 2000000
                  bw: 10000
      - !datacenter
          name: micro_dc_ucd
          type: micro
          connect_to:
            - edge_dc_frankfurt
            - cloud_dc
          amount: 1
          hosts:
            - !host
                amount: 3
                pes: 6
                pe_mips: 60
                ram: 65536
                storage: 1000000
                bw: 1000
                vms:
                  - !vm
                    amount: 1
                    pes: 6
                    pe_mips: 60
                    ram: 65536
                    size: 1000000
                    bw: 1000
      - !datacenter
          name: micro_dc_dcu
          type: micro
          connect_to:
            - edge_dc_frankfurt
            - cloud_dc
          amount: 1
          hosts:
            - !host
                amount: 2
                pes: 6
                pe_mips: 60
                ram: 65536
                storage: 1000000
                bw: 1000
                vms:
                  - !vm
                    amount: 1
                    pes: 6
                    pe_mips: 60
                    ram: 65536
                    size: 1000000
                    bw: 1000
      - !datacenter
          name: micro_dc_eur
          type: micro
          connect_to:
            - edge_dc_frankfurt
            - cloud_dc
          amount: 1
          hosts:
            - !host
                amount: 3
                pes: 6
                pe_mips: 60
                ram: 65536
                storage: 1000000
                bw: 1000
                vms:
                  - !vm
                    amount: 1
                    pes: 6
                    pe_mips: 60
                    ram: 65536
                    size: 1000000
                    bw: 1000
  seed: 1234
  timestep_interval: 1.0
  min_time_between_events: 0.1
  max_episode_length: 150
  split_large_jobs: true
  clear_created_lists: false
  vm_startup_delay: 0.0
  vm_shutdown_delay: 0.0
  paying_for_the_full_hour: false
  save_experiment: true
  base_log_dir: logs
  mode: train
  max_jobs_waiting: 20
  vm_allocation_policy: bestfit
  cloudlet_to_dc_assignment_policy: rl
  cloudlet_to_vm_assignment_policy: most-free-cores
  state_space_type: dcid-dctype-freevmpes-per-host
  enable_autoencoder_observation: true
  autoencoder_latent_dim: 32
  freeze_inactive_input_layer_weights: false # keep false if autoencoder is used
  algorithm: MaskablePPO
  max_datacenters: 6
  max_hosts: 32
  max_host_pes: 64
  job_trace_filename: jobs_with_locations.csv
  timesteps: 200000
  n_rollout_steps: 2048
  reward_jobs_placed_coef: 0.333
  reward_quality_coef: 0.333
  reward_deadline_violation_coef: 0.333
  # reward_job_wait_coef: 0.25
  # reward_running_vm_cores_coef: 0.25
  # reward_unutilized_vm_cores_coef: 0.25
  # reward_invalid_coef: 0.25

experiment_1:
    experiment_dir: euromlsys
    experiment_name: debug_use_autoencoder