version: '3.1'
services:
  gateway:
    image: gateway:1.9.1
    container_name: gateway
    restart: always
    environment:
      CLOUDSIM_GATEWAY_HOST: gateway
      CLOUDSIM_GATEWAY_PORT: 25333
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/external"
      #TEST_FILE: KTH-SP2-1996-2.1-cln.swf
    ports:
      - 25333:25333

  # database:
  #   image: postgres
  #   container_name: database
  #   restart: always
  #   environment:
  #     POSTGRES_USER: samm
  #     POSTGRES_PASSWORD: samm_secret
  #     POSTGRES_DB: samm_db
  #   ports:
  #     - 5432:5432

  manager: &cpu
    profiles: [""]
    image: manager:0.10
    container_name: manager
    restart: always
    build: rl-manager
    depends_on:
      - gateway
      # - database
    environment:
      CLOUDSIM_GATEWAY_HOST: gateway
      CLOUDSIM_GATEWAY_PORT: 25333
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: samm
      POSTGRES_PASSWORD: samm_secret
      POSTGRES_DB: samm_db
      #TEST_CASE: model
      #BATCH_SIZE: 128
      #EPISODES_CNT: 25
    volumes:
      - ./model-storage:/mgr/storage
      - ./rl-manager/mnt:/mgr/mnt
      - ~/tb-logs:/mgr/tb-logs
    command: python3 mnt/learn.py ${ALGORITHM} ${TIMESTEPS}

  manager-gpu:
    <<: *cpu
    profiles: ["gpu"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
