version: '3.1'
services:
  # uses port 25333
  gateway:
    image: gateway:1.9.1
    container_name: gateway
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/external"

  # # uses port 5432
  # database:
  #   image: postgres
  #   container_name: database
  #   restart: always
  #   environment:
  #     POSTGRES_USER: samm
  #     POSTGRES_PASSWORD: samm_secret
  #     POSTGRES_DB: samm_db

  manager: &cpu
    profiles: [""]
    image: manager:0.10
    container_name: manager
    build: rl-manager
    depends_on:
      - gateway
      # - database
    environment:
      CLOUDSIM_GATEWAY_HOST: gateway
      CLOUDSIM_GATEWAY_PORT: 25333
      # POSTGRES_HOST: database
      # POSTGRES_PORT: 5432
      # POSTGRES_USER: samm
      # POSTGRES_PASSWORD: samm_secret
      # POSTGRES_DB: samm_db
      # TEST_CASE: model
      # BATCH_SIZE: 128
      # EPISODES_CNT: 25
    volumes:
      - ./model-storage:/mgr/storage
      - ./rl-manager/mnt:/mgr/mnt
      - ./tb-logs:/mgr/tb-logs
    command: python3 mnt/learn.py ${ALGORITHM} ${TIMESTEPS}

  manager-gpu:
    <<: *cpu
    profiles: ["gpu"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
