version: '3.1'
services:
  # uses port 25333
  gateway:
    image: gateway:1.9.1
    container_name: gateway
    volumes:
      - ./logs:/app/logs

  # # uses port 5432
  # database:
  #   image: postgres
  #   container_name: database
  #   restart: always
  #   environment:
  #     POSTGRES_USER: samm
  #     POSTGRES_PASSWORD: samm_secret
  #     POSTGRES_DB: samm_db

  manager: &cpu
    profiles: [""]
    image: manager:0.10
    container_name: manager
    build: rl-manager
    depends_on:
      - gateway
      # - database
    environment:
      CLOUDSIM_GATEWAY_HOST: gateway
      CLOUDSIM_GATEWAY_PORT: 25333
      # POSTGRES_HOST: database
      # POSTGRES_PORT: 5432
      # POSTGRES_USER: samm
      # POSTGRES_PASSWORD: samm_secret
      # POSTGRES_DB: samm_db
      # TEST_CASE: model
      # BATCH_SIZE: 128
      # EPISODES_CNT: 25
    volumes:
      - ./logs:/mgr/logs
      - ./rl-manager/mnt:/mgr/mnt
    command: >
      python3 mnt/run.py 
      --algo=${ALGO}
      --pretrain-env=${PRETRAIN_ENV}
      --pretrain-timesteps=${PRETRAIN_TIMESTEPS}
      --transfer-env=${TRANSFER_ENV}
      --transfer-timesteps=${TRANSFER_TIMESTEPS}
      --simulation-speedup=${SIMULATION_SPEEDUP}
      --reward-job-wait-coef=${REWARD_JOB_WAIT_COEF}
      --reward-utilization-coef=${REWARD_UTILIZATION_COEF}
      --reward-invalid-coef=${REWARD_INVALID_COEF}
      --max-pes-per-job=${MAX_PES_PER_JOB}

  manager-cuda:
    <<: *cpu
    profiles: ["cuda"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
