services:
  # uses port 25333 by default
  gateway:
    image: gateway:2.0.0
    container_name: gateway

  manager: &cpu
    profiles: [ "" ]
    image: manager:0.10
    # container_name: manager
    build: rl-manager
    depends_on:
      - gateway
    volumes:
      - ./logs:/mgr/logs
      - ./rl-manager/mnt:/mgr/mnt
      - /run/docker.sock:/run/docker.sock:ro
    command: python mnt/entrypoint.py

  manager-cuda:
    <<: *cpu
    profiles: [ "cuda" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
