services: # uses port 25333
  gateway:
    image: gateway:2.0.0
    container_name: gateway
    volumes:
      - ./logs:/app/logs

  manager: &cpu
    profiles: [""]
    image: manager:0.10
    container_name: manager
    build: rl-manager
    depends_on:
      - gateway
    environment:
      CLOUDSIM_GATEWAY_HOST: gateway
      CLOUDSIM_GATEWAY_PORT: 25333
    volumes:
      - ./logs:/mgr/logs
      - ./rl-manager/mnt:/mgr/mnt
    command: >
      python3 mnt/run.py
      --algo=${ALGO}
      --max-timesteps-per-episode=${MAX_TIMESTEPS-PER-EPISODE}
      --pretrain-timesteps=${PRETRAIN_TIMESTEPS}
      --pretrain-hosts=${PRETRAIN_HOSTS}
      --pretrain-host-pes=${PRETRAIN_HOST_PES}
      --pretrain-host-pe-mips=${PRETRAIN_HOST_PE_MIPS}
      --pretrain-job-trace-filename=${PRETRAIN_JOB_TRACE_FILENAME}
      --pretrain-max-job-pes=${PRETRAIN_MAX_JOB_PES}
      --pretrain-reward-job-wait-coef=${PRETRAIN_REWARD_JOB_WAIT_COEF}
      --pretrain-reward-util-coef=${PRETRAIN_REWARD_UTIL_COEF}
      --pretrain-reward-invalid-coef=${PRETRAIN_REWARD_INVALID_COEF}
      --pretrain-dir=${PRETRAIN_DIR}
      --transfer-timesteps=${TRANSFER_TIMESTEPS}
      --transfer-hosts=${TRANSFER_HOSTS}
      --transfer-host-pes=${TRANSFER_HOST_PES}
      --transfer-host-pe-mips=${TRANSFER_HOST_PE_MIPS}
      --transfer-job-trace-filename=${TRANSFER_JOB_TRACE_FILENAME}
      --transfer-max-job-pes=${TRANSFER_MAX_JOB_PES}
      --transfer-reward-job-wait-coef=${TRANSFER_REWARD_JOB_WAIT_COEF}
      --transfer-reward-util-coef=${TRANSFER_REWARD_UTIL_COEF}
      --transfer-reward-invalid-coef=${TRANSFER_REWARD_INVALID_COEF}
      --simulation-speedup=${SIMULATION_SPEEDUP}


  manager-cuda:
    <<: *cpu
    profiles: ["cuda"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
