services:
  gateway:
    image: gateway:2.0.0
    container_name: gateway
    volumes:
      - ./logs:/app/logs

  manager: &cpu
    profiles: [ "" ]
    image: manager:0.10
    # container_name: manager # disabled to allow multiple instances
    build:
      context: .
      dockerfile: rl-manager/Dockerfile
    depends_on:
      - gateway
    volumes:
      - ./config.yml:/mgr/config.yml
      - ./rl-manager/mnt:/mgr/mnt
      - ./logs:/mgr/logs
      - /run/docker.sock:/run/docker.sock:ro
    command: python mnt/entrypoint.py

  manager-cuda:
    <<: *cpu
    profiles: [ "cuda" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
