# train_model_dir: applicable only if mode == [transfer|test]
# globals.java_log_destination: [none, stdout, file, stdout-file] - if file, logs are written to a file, if stdout-file, logs are written to both stdout and a file
# globals.junit_output_show: [true, false] - if true, junit test results are printed to stdout
# globals.java_log_level: [TRACE, DEBUG, INFO, WARNING, ERROR]
# seed: random or any integer
# base_log_dir: parent directory for all logs
# experiment_dir: parent directory for a set of experiments
# experiment_name: name of the experiment
# mode: [train, test, transfer]
# vm_allocation_policy: [rl, rule-based]
# cloudlet_to_dc_assignment_policy: [earliest-shortest-to-most-free-dc, random-to-most-free-dc, earliest-most-critical-to-nearest-dc, rl]
# cloudlet_to_vm_assignment_policy: [most-free-cores]
# algorithm: [any stable-baselines3 or sb3-contrib algorithm if vm_allocation_policy == rl, minimize-queue, minimize-allocated, minimize-unutilized if vm_allocation_policy == rule-based]

# if you make any changes in java_log_leve, java_log_destination or java_output_show,
#  you need to execute make build-gateway for the changes to take effect
globals:
    # applies_to: JOB_PLACEMENT
    attached: false
    # applies_to: JOB_PLACEMENT
    gpu: true
    # applies_to: JOB_PLACEMENT
    java_log_level: INFO
    # applies_to: JOB_PLACEMENT
    java_log_destination: none
    # applies_to: JOB_PLACEMENT
    junit_output_show: false
    # applies_to: JOB_PLACEMENT
    num_cpu: 16

common:
  # applies_to: JOB_PLACEMENT
  timestep_interval: 1.0
  # applies_to: JOB_PLACEMENT
  min_time_between_events: 0.1
  # applies_to: JOB_PLACEMENT
  max_episode_length: 150
  # applies_to: JOB_PLACEMENT
  split_large_jobs: true
  # applies_to: JOB_PLACEMENT
  clear_created_lists: false
  # applies_to: JOB_PLACEMENT
  vm_startup_delay: 0.0
  # applies_to: JOB_PLACEMENT
  vm_shutdown_delay: 0.0
  # applies_to: JOB_PLACEMENT
  paying_for_the_full_hour: false
  # applies_to: JOB_PLACEMENT
  save_experiment: true
  # applies_to: JOB_PLACEMENT
  base_log_dir: logs
  # applies_to: JOB_PLACEMENT
  batch_size: 64
  # applies_to: JOB_PLACEMENT
  vm_allocation_policy: bestfit
  # applies_to: JOB_PLACEMENT
  cloudlet_to_dc_assignment_policy:  earliest-most-critical-to-nearest-dc
  # applies_to: JOB_PLACEMENT
  cloudlet_to_vm_assignment_policy: most-free-cores
  # applies_to: JOB_PLACEMENT
  state_space_type: dcid-dctype-freevmpes-per-host
  # applies_to: JOB_PLACEMENT
  autoencoder_infr_obs: false
  # applies_to: JOB_PLACEMENT
  autoencoder_infr_obs_latent_dim: 32
  # applies_to: JOB_PLACEMENT
  freeze_inactive_input_layer_weights: false
  # applies_to: JOB_PLACEMENT
  max_datacenters: 6
  # applies_to: JOB_PLACEMENT
  max_datacenter_types: 3
  # applies_to: JOB_PLACEMENT
  max_hosts: 40
  # applies_to: JOB_PLACEMENT
  max_host_pes: 64
  # applies_to: JOB_PLACEMENT
  max_jobs_waiting: 50
  # applies_to: JOB_PLACEMENT
  max_job_pes: 16
  # applies_to: JOB_PLACEMENT
  max_job_delay_sensitivity_levels: 3
  # applies_to: JOB_PLACEMENT
  max_job_deadline: 20
  # applies_to: JOB_PLACEMENT
  timesteps: 2048
  # applies_to: JOB_PLACEMENT
  n_rollout_steps: 2048
  # applies_to: JOB_PLACEMENT
  reward_jobs_placed_coef: 0.333
  # applies_to: JOB_PLACEMENT
  reward_quality_coef: 0.333
  # applies_to: JOB_PLACEMENT
  reward_deadline_violation_coef: 0.333
  # applies_to: JOB_PLACEMENT
  seed: 1234
  # applies_to: JOB_PLACEMENT
  algorithm: PPO
  # applies_to: JOB_PLACEMENT
  mode: train

# experiment_1:
#   datacenters:
#     !include datacenters_b.yml
#   experiment_dir: euromlsys/earliest-most-critical-to-nearest-dc
#   experiment_name: env_b
#   job_trace_filename: euromlsys_jobs_first_50.csv

experiment_1:
  datacenters:
    !include datacenters_a.yml
  experiment_dir: euromlsys/earliest-most-critical-to-nearest-dc
  experiment_name: env_a
  job_trace_filename: euromlsys_jobs_first_50.csv

experiment_2:
  datacenters:
    !include datacenters_c.yml
  experiment_dir: euromlsys/earliest-most-critical-to-nearest-dc
  experiment_name: env_c
  job_trace_filename: euromlsys_jobs_three_locs_first_50.csv
