# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cloudsimplus_pb2 as cloudsimplus__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloudsimplus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CloudSimServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createSimulation = channel.unary_unary(
                '/daislab.cspg.CloudSimService/createSimulation',
                request_serializer=cloudsimplus__pb2.CreateRequest.SerializeToString,
                response_deserializer=cloudsimplus__pb2.CreateResponse.FromString,
                _registered_method=True)
        self.reset = channel.unary_unary(
                '/daislab.cspg.CloudSimService/reset',
                request_serializer=cloudsimplus__pb2.ResetRequest.SerializeToString,
                response_deserializer=cloudsimplus__pb2.ResetResult.FromString,
                _registered_method=True)
        self.step = channel.unary_unary(
                '/daislab.cspg.CloudSimService/step',
                request_serializer=cloudsimplus__pb2.StepRequest.SerializeToString,
                response_deserializer=cloudsimplus__pb2.StepResult.FromString,
                _registered_method=True)
        self.batchStep = channel.unary_unary(
                '/daislab.cspg.CloudSimService/batchStep',
                request_serializer=cloudsimplus__pb2.BatchStepRequest.SerializeToString,
                response_deserializer=cloudsimplus__pb2.BatchStepResponse.FromString,
                _registered_method=True)
        self.close = channel.unary_unary(
                '/daislab.cspg.CloudSimService/close',
                request_serializer=cloudsimplus__pb2.CloseRequest.SerializeToString,
                response_deserializer=cloudsimplus__pb2.CloseResponse.FromString,
                _registered_method=True)
        self.render = channel.unary_unary(
                '/daislab.cspg.CloudSimService/render',
                request_serializer=cloudsimplus__pb2.RenderRequest.SerializeToString,
                response_deserializer=cloudsimplus__pb2.RenderResponse.FromString,
                _registered_method=True)
        self.ping = channel.unary_unary(
                '/daislab.cspg.CloudSimService/ping',
                request_serializer=cloudsimplus__pb2.PingRequest.SerializeToString,
                response_deserializer=cloudsimplus__pb2.PongResponse.FromString,
                _registered_method=True)


class CloudSimServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def batchStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def render(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudSimServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.createSimulation,
                    request_deserializer=cloudsimplus__pb2.CreateRequest.FromString,
                    response_serializer=cloudsimplus__pb2.CreateResponse.SerializeToString,
            ),
            'reset': grpc.unary_unary_rpc_method_handler(
                    servicer.reset,
                    request_deserializer=cloudsimplus__pb2.ResetRequest.FromString,
                    response_serializer=cloudsimplus__pb2.ResetResult.SerializeToString,
            ),
            'step': grpc.unary_unary_rpc_method_handler(
                    servicer.step,
                    request_deserializer=cloudsimplus__pb2.StepRequest.FromString,
                    response_serializer=cloudsimplus__pb2.StepResult.SerializeToString,
            ),
            'batchStep': grpc.unary_unary_rpc_method_handler(
                    servicer.batchStep,
                    request_deserializer=cloudsimplus__pb2.BatchStepRequest.FromString,
                    response_serializer=cloudsimplus__pb2.BatchStepResponse.SerializeToString,
            ),
            'close': grpc.unary_unary_rpc_method_handler(
                    servicer.close,
                    request_deserializer=cloudsimplus__pb2.CloseRequest.FromString,
                    response_serializer=cloudsimplus__pb2.CloseResponse.SerializeToString,
            ),
            'render': grpc.unary_unary_rpc_method_handler(
                    servicer.render,
                    request_deserializer=cloudsimplus__pb2.RenderRequest.FromString,
                    response_serializer=cloudsimplus__pb2.RenderResponse.SerializeToString,
            ),
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=cloudsimplus__pb2.PingRequest.FromString,
                    response_serializer=cloudsimplus__pb2.PongResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'daislab.cspg.CloudSimService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('daislab.cspg.CloudSimService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CloudSimService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daislab.cspg.CloudSimService/createSimulation',
            cloudsimplus__pb2.CreateRequest.SerializeToString,
            cloudsimplus__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daislab.cspg.CloudSimService/reset',
            cloudsimplus__pb2.ResetRequest.SerializeToString,
            cloudsimplus__pb2.ResetResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daislab.cspg.CloudSimService/step',
            cloudsimplus__pb2.StepRequest.SerializeToString,
            cloudsimplus__pb2.StepResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def batchStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daislab.cspg.CloudSimService/batchStep',
            cloudsimplus__pb2.BatchStepRequest.SerializeToString,
            cloudsimplus__pb2.BatchStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daislab.cspg.CloudSimService/close',
            cloudsimplus__pb2.CloseRequest.SerializeToString,
            cloudsimplus__pb2.CloseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def render(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daislab.cspg.CloudSimService/render',
            cloudsimplus__pb2.RenderRequest.SerializeToString,
            cloudsimplus__pb2.RenderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daislab.cspg.CloudSimService/ping',
            cloudsimplus__pb2.PingRequest.SerializeToString,
            cloudsimplus__pb2.PongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
