services:
  manager: &cpu
    image: manager:0.11
    container_name: manager
    environment: # passing defaults to avoid warnings
      - EXPERIMENT_ID=${EXPERIMENT_ID:-1}
      - NUM_EXPERIMENTS=${NUM_EXPERIMENTS:-1}
      - CUBLAS_WORKSPACE_CONFIG=:4096:8
      - CUDA_LAUNCH_BLOCKING=1
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      - JAVA_LOG_DESTINATION=${JAVA_LOG_DESTINATION:-stdout}
      - JAVA_LOG_LEVEL=${JAVA_LOG_LEVEL:-INFO}
    build:
      context: rl-manager
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
        PAPER_DIR: ${PAPER_DIR:-main}
    volumes:
      - ./rl-manager/utils:/mgr/utils
      - ./rl-manager/gym_cloudsimplus:/mgr/gym_cloudsimplus
      - ./rl-manager/startup.sh:/common/rl-manager/startup.sh
      - ./traces:/mgr/traces
      - ./rl-manager/train.py:/mgr/train.py
      - ./rl-manager/transfer.py:/mgr/transfer.py
      - ./rl-manager/test.py:/mgr/test.py
      - ./rl-manager/entrypoint.py:/mgr/entrypoint.py
      - ../common/logs:/mgr/logs
      - ./rl-manager/callbacks:/mgr/callbacks
      - ../papers/${PAPER_DIR:-main}/config.yml:/mgr/config.yml
      - ../papers/${PAPER_DIR:-main}/cloudsimplus-gateway/build/libs:/app/cloudsimplus-gateway/build/libs:ro
      - ../common/topologies:/mgr/topologies:ro
      - /run/docker.sock:/run/docker.sock:ro
    command: bash /common/rl-manager/startup.sh

  manager-cuda:
    <<: *cpu
    container_name: manager-cuda
    profiles: ["cuda"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
